name: Build and deploy - wireservers-food-api

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: read
    defaults:
      run:
        working-directory: apis/food-api

    steps:
      - uses: actions/checkout@v4
        with:
          submodules: recursive

      - name: Set up .NET Core
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: '10.x'

      - name: Build with dotnet
        run: dotnet build BringTheDiet.Api.csproj --configuration Release

      - name: dotnet publish
        run: dotnet publish BringTheDiet.Api.csproj -c Release -o ${{ env.DOTNET_ROOT }}/myapp

      - name: Upload artifact for deployment job
        uses: actions/upload-artifact@v4
        with:
          name: .net-app
          path: ${{ env.DOTNET_ROOT }}/myapp

  deploy:
    runs-on: ubuntu-latest
    needs: build
    permissions:
      id-token: write
      contents: read

    steps:
      - name: Download artifact from build job
        uses: actions/download-artifact@v4
        with:
          name: .net-app

      - name: Login to Azure
        uses: azure/login@v2
        with:
          client-id: ${{ secrets.AZUREAPPSERVICE_CLIENTID_A8533FA2F56D48EFA8F8DD96B56D0BC8 }}
          tenant-id: ${{ secrets.AZUREAPPSERVICE_TENANTID_439DC8A532FC420189E5280C50C9B696 }}
          subscription-id: ${{ secrets.AZUREAPPSERVICE_SUBSCRIPTIONID_407FB1216C6044F2A27A3D0CA61CE747 }}

      - name: Deploy to Azure Web App
        id: deploy-to-webapp
        uses: azure/webapps-deploy@v3
        with:
          app-name: 'wireservers-food-api'
          slot-name: 'Production'
          package: .
